### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by sivar2311**

### CODE REVIEW

**Comment by sivar2311** [comment]
See my comments on the individual commits

**Review by nzwildcode — COMMENTED** [review]
Thanks for the pull request. Let me test this on my rig, then I will merge it 😁👍.

**Comment by nzwildcode** [comment]
Works wonderfully! Merged!

image

**Comment by sivar2311** [comment]
I know, because I have tested it 😉

By the way: I created a repo with settings for various (official) ESP32-S3 modules for the platformio.ini:
https://github.com/sivar2311/ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations

This allows you to use the default `board = esp32-s3-devkitc-1`. 
No additional boards.json is needed then.

**Comment by nzwildcode** [comment]
Amazing! Thank you for all your contributions. That will indeed help programmers. We should make a program to challenge the full FLASH and RAM available on the respective boards. What do you think?

**Comment by sivar2311** [comment]
Sorry, I don't understand.
What's your intention?

Everything works fine if the configuration is correct. Do you still have issues?

**Comment by nzwildcode** [comment]
Apologies for my previous impromptu response. It would be beneficial to design a program to perform memory diagnostic tests by writing to and reading from both flash memory and RAM. With this idea in mind, I've created a prototype which is available at:
https://github.com/nzwildcode/ESP32-S3-DEVKITC-1-N32R8V-RAM_FLASH-_Tester
In this program, I've implemented memory tests based on the configurations from your project:
https://github.com/sivar2311/ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations

**Pull request merged**
